server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam-board
    username: root
    password: 2738

  jpa:
    hibernate:
      ddl-auto: validate #create
    show-sql: true
---

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 347103568395-afdtduhk73cfdia79ci402l0qrqkpusr.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          naver:
            clientId: xFiMPrT1KmDcYLw4eh_3
            clientSecret: 2zNk4eLa7d
            scope:
              - name
              - email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost/login/oauth2/code/naver


          kakao:
            client-id: 10d6d2824a43146377e034e12a05ea26
            clientSecret: optFX28piH3kW67qUQpgOxcpCFkPbWfl
            redirectUri: http://localhost/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            #로그인창 보이기
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            #프로필 정보 받을 곳
            user-name-attribute: response
            #회원정보를 json으로 받아올 때 response라는 키값으로 리턴.

          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


